package main

var helpText = []string{
	"Fl(ow)(T)erm Help",
	"=================",
	"",
	"",
	"Navigation:",
	"-----------",
	"  h/←/j/↓/k/↑/l/→  Move cursor around the screen",
	"  Shift+h/j/k/l    Move cursor 2x faster (hold Shift with direction keys)",
	"",
	"Box Operations:",
	"---------------",
	"  b                Create new box at cursor position",
	"  e                Edit text in box under cursor",
	"  r                Resize box under cursor",
	"  m                Move box under cursor",
	"  d                Delete box under cursor",
	"  c                Copy box under cursor",
	"  p                Paste copied box at cursor position",
	"",
	"Text Operations:",
	"----------------",
	"  t                Enter text at cursor position",
	"  e                Edit text under cursor",
	"  m                Move text under cursor",
	"  d                Delete text under cursor",
	"",
	"Resize Mode:",
	"------------",
	"  h/←/j/↓/k/↑/l/→  Resize box",
	"  Shift+h/j/k/l    Resize box 2x faster",
	"  Enter            Confirm edit and return to normal mode",
	"  Esc   	        Canceland return to normal mode",
	"",
	"Move Mode:",
	"----------",
	"  h/←/j/↓/k/↑/l/→  Move object around the screen",
	"  Shift+h/j/k/l    Move object 2x faster",
	"  Enter            Finish moving and return to normal mode",
	"  Escape           Cancel move and return to normal mode",
	"",
	"Note: Selected boxes (being resized/moved) are highlighted with # borders",
	"Another note: Resizing/moving boxes with connections is a little wonky,",
	"              when in doubt, delete the lines and re-connect the boxes ¯\\_(ツ)_/¯",
	"",
	"Connection Operations:",
	"---------------------",
	"  a                Start/finish connection creation",
	"                   - Press 'a' on a box or line to start",
	"                   - Press 'a' on empty space to add waypoint",
	"                   - Press 'a' on a box or line to finish",
	"                   - Connections can start/end at boxes or lines",
	"  A                Toggle arrow state on connection line under cursor",
	"                   - Cycles through: no arrows → to arrow → from arrow → both arrows",
	"                   Note: Sometimes the arrows flip around. Redrawing the line fixes it.",
	"",
	"File Operations:",
	"----------------",
	"  s                Save flowchart",
	"  S                Export as PNG image (experimental and janky)",
	"  o                Load a saved flowchart in current buffer",
	"  O                Load a saved flowchart in new buffer",
	"",
	"Buffer Operations:",
	"------------------",
	"  {                Switch to previous buffer",
	"  }                Switch to next buffer",
	"  n                Create new chart in current buffer",
	"  N                Create new chart in new buffer",
	"  x                Close current buffer",
	"",
	"General:",
	"  u                Undo last action",
	"  U                Redo last undone action",
	"  Esc           	Clear selection/cancel current operation",
	"  ?                Toggle this help screen",
	"  q/Ctrl+C         Quit Flerm",
	"",
	"========== Thanks for trying Flerm! ==========",
}

