package main

var helpText = []string{
	"Fl(ow)(T)erm Help",
	"=================",
	"",
	"",
	"Navigation:",
	"-----------",
	"  h/←/j/↓/k/↑/l/→  Move cursor around the screen",
	"  Shift+h/j/k/l    Move cursor 2x faster (hold Shift with direction keys)",
	"",
	"Box Operations:",
	"---------------",
	"  b                Create new box at cursor position",
	"  T (Shift+t)      Add/edit title on box under cursor",
	"  e                Edit text in box under cursor",
	"  r                Resize box under cursor",
	"  m                Move box under cursor",
	"  d                Delete box under cursor",
	"  c                Copy box under cursor",
	"  p                Paste copied box at cursor position",
	"  Z (Shift+z)      Cycle box z-level (0-3) for drop shadow effect",
	"  Tab              Cycle border style (ASCII, Single, Double, Rounded)",
	"  B (Shift+b)      Box jump - quickly jump to any box by number",
	"  M (Shift+m)      Enter multi-select mode to select multiple boxes",
	"",
	"Text Operations:",
	"----------------",
	"  t                Enter text at cursor position",
	"  e                Edit text under cursor",
	"  m                Move text under cursor",
	"  d                Delete text under cursor",
	"",
	"Resize Mode:",
	"------------",
	"  h/←/j/↓/k/↑/l/→  Resize box",
	"  Shift+h/j/k/l    Resize box 2x faster",
	"  Enter            Confirm edit and return to normal mode",
	"  Esc   	        Canceland return to normal mode",
	"",
	"Move Mode:",
	"----------",
	"  h/←/j/↓/k/↑/l/→  Move object around the screen",
	"  Shift+h/j/k/l    Move object 2x faster",
	"  Enter            Finish moving and return to normal mode",
	"  Escape           Cancel move and return to normal mode",
	"",
	"Note: Selected boxes (being resized/moved) are highlighted with # borders",
	"Another note: Resizing/moving boxes with connections is a little wonky,",
	"              when in doubt, delete the lines and re-connect the boxes ¯\\_(ツ)_/¯",
	"",
	"Connection Operations:",
	"---------------------",
	"  a                Start/finish connection creation",
	"                   - Press 'a' on a box or line to start",
	"                   - Press 'a' on empty space to add waypoint",
	"                   - Press 'a' on a box or line to finish",
	"                   - Connections can start/end at boxes or lines",
	"  A                Toggle arrow state on connection line under cursor",
	"                   - Cycles through: no arrows → to arrow → from arrow → both arrows",
	"                   Note: Sometimes the arrows flip around. Redrawing the line fixes it.",
	"",
	"Highlight Mode:",
	"---------------",
	"  Space            Enter highlight mode",
	"                   - When in highlight mode on a box: cycle highlighting",
	"                     (divider → border → both → clear)",
	"  Tab              Cycle through 8 highlight colors",
	"  h/j/k/l          Move cursor and leave colored trail",
	"  d    						Delete the highlight directly under the cursor",
	"  D    						Delete all highlights from an element",
	"  Enter            Highlight entire element at cursor (box, text, or connection)",
	"  Esc              Exit highlight mode",
	"",
	"File Operations:",
	"----------------",
	"  s                Save flowchart",
	"  S                Export as PNG image (experimental and janky)",
	"  o                Load a saved flowchart in current buffer",
	"  O                Load a saved flowchart in new buffer",
	"",
	"Buffer Operations:",
	"------------------",
	"  {                Switch to previous buffer",
	"  }                Switch to next buffer",
	"  n                Create new chart in current buffer",
	"  N                Create new chart in new buffer",
	"  x                Close current buffer",
	"",
	"General:",
	"--------",
	"  u                Undo last action",
	"  U                Redo last undone action",
	"  z                Toggle pan mode (scroll canvas instead of moving cursor)",
	"  Esc           	Clear selection/cancel current operation",
	"  ?                Toggle this help screen",
	"  q/Ctrl+C         Quit Flerm",
	"",
	"",
	"============== MIND MAP MODE ==============",
	"",
	"Press Space in normal mode to switch between Flerm and Mind Map modes.",
	"",
	"Navigation:",
	"-----------",
	"  h/←/j/↓/k/↑/l/→  Move cursor freely",
	"  Shift+h/j/k/l    Move cursor 2x faster",
	"  n or B           Jump to node by number",
	"  g                Go to root node",
	"  [                Go to first sibling",
	"  ]                Go to last sibling",
	"",
	"Node Creation:",
	"--------------",
	"  i                Create root node at cursor position",
	"  o or Enter       Create sibling node (below current node)",
	"  O or Tab         Create child node (to the right of current node)",
	"",
	"Node Editing:",
	"-------------",
	"  e or a           Edit text in current node",
	"                   (Ctrl+S to save, Enter for newline, Esc to cancel)",
	"  t                Toggle border style (None/ASCII/Single/Double/Rounded)",
	"  d                Delete node and all its children",
	"",
	"Node Organization:",
	"------------------",
	"  K (Shift+k)      Move node up among siblings",
	"  J (Shift+j)      Move node down among siblings",
	"  y                Yank (copy) node",
	"  Y (Shift+y)      Yank node with all children",
	"  p                Paste as child of current node",
	"  P (Shift+p)      Paste as sibling of current node",
	"",
	"Other:",
	"------",
	"  Space            Switch to Flerm mode",
	"  z                Toggle pan mode",
	"  s                Save mind map",
	"  o                Open saved file",
	"  ?                Toggle this help screen",
	"  q/Ctrl+C         Quit",
	"",
	"========== Thanks for trying Flerm! ==========",
}
